package net.liftweb.proto

/*                                                *\
  (c) 2006-2007 WorldWide Conferencing, LLC
  Distributed under an Apache License
  http://www.apache.org/licenses/LICENSE-2.0
\*                                                */

import net.liftweb.mapper.{Mapper, MappedField, IndexedField, MetaMapper, ForeignKey}
import java.sql.{ResultSet, Types}
import java.lang.reflect.Method
import net.liftweb.util.Helpers._
import java.lang.Long

class MappedLongForeignKey[T,O](owner: Mapper[T], foreign: MetaMapper[O]) extends MappedLong[T](owner) with ForeignKey[long] {
  def defined_? = i_get_! != defaultValue
      
  override def getJDBCFriendly(field : String) = if (defined_?) new Long(get) else null
}

class MappedLongIndex[T](owner : Mapper[T]) extends MappedLong[T](owner) with IndexedField[long] {

  override def write_permission_? = false // not writable
  
  override def db_index_? = true

  def defined_? = i_get_! != defaultValue

  override def db_autogenerated_index_? = true
  
  override def defaultValue = -1L
  
  override def db_index_field_indicates_saved_? = {i_get_! != defaultValue}
  
  def makeKeyJDBCFriendly(in : long) = new java.lang.Long(in)
  
  def convertKey(in : String) : Option[long] = {
    if (in eq null) None
    try {
      val what = if (in.startsWith(name + "=")) in.substring((name + "=").length) else in
      Some(Long.parseLong(what))
    } catch {
      case _ => {None}
    }
  }
  
  override def db_display_? = false
  
  def convertKey(in : long) : Option[long] = {
    if (in < 0L) None
    else Some(in)
  }
  
  def convertKey(in : int) : Option[long] = {
    if (in < 0) None
    else Some(in)
  }
  
  def convertKey(in : AnyRef) : Option[long] = {
    if ((in eq null) || (in eq None)) None
    try {
      convertKey(in.toString)
    } catch {
      case _ => {None}
    }                                         
  }
}


class MappedLong[T](val owner : Mapper[T]) extends MappedField[long, T] {
  private var data : long = defaultValue
  def defaultValue = 0L

  /**
   * Get the JDBC SQL Type for this field
   */
  def getTargetSQLType(field : String) = Types.INTEGER

  protected def i_get_! = data
  
  protected def i_set_!(value : long) : long = {
    if (value != data) {
      data = value
      this.dirty_?( true)
    }
    data
  }
  override def read_permission_? = true
  override def write_permission_? = true
  
  def convertToJDBCFriendly(value: long): Object = new Long(value)
      
      
  def getJDBCFriendly(field : String) = new Long(get)

  def ::=(f : Any) : long = {
    this := tryn {if (f != null) Long.parseLong(f.toString) else 0L}
  }
  protected def i_obscure_!(in : long) = 0L
  
  def buildSetActualValue(accessor : Method, inst : AnyRef, columnName : String) : (Mapper[T], AnyRef) => unit = {
    inst match {
      case null => {(inst : Mapper[T], v : AnyRef) => {val tv = getField(inst, accessor); tv.set(0L); tv.resetDirty}}
      case _ if (inst.isInstanceOf[Number]) => {(inst : Mapper[T], v : AnyRef) => {val tv = getField(inst, accessor); tv.set(if (v == null) 0L else v.asInstanceOf[Number].longValue); tv.resetDirty}}
      case _ => {(inst : Mapper[T], v : AnyRef) => {val tv = getField(inst, accessor); tv.set(tryn(Long.parseLong(v.toString))); tv.resetDirty}}
    }
  }
}

